spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_connection_pool
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    hikari:
      maximum-pool-size: 10

database:
  connection:
    pooling: false
